#!/bin/bash
set -e

macos() {
    # Install Homebrew
    if ! which brew > /dev/null; then
        /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    fi

    if ! which ansible-playbook > /dev/null; then
        brew install ansible
    fi

    ansible-playbook macos.yml -i <(echo "[localhost] localhost ansible_connection=local") $ANSIBLE_OPTS
}

linux() {
    if ! which ansible-playbook > /dev/null; then
        sudo apt update
        sudo apt install -qy ansible
    fi

    ansible-playbook ubuntu.yml -i <(echo "[localhost] localhost ansible_connection=local") $ANSIBLE_OPTS
}

if [[ "$(uname)" == "Darwin" ]]; then
    macos
fi

if [[ "$(uname)" == "Linux" ]]; then
    linux
fi