#!/bin/bash
set -e

macos() {
    if ! which brew > /dev/null; then
        /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    fi

    if ! which ansible-playbook > /dev/null; then
        brew install ansible
    fi

    PATH="/Applications/Visual Studio Code.app/Contents/Resources/app/bin:$PATH"
    ansible-playbook ansible/macos.yml -i <(echo "[localhost] localhost ansible_connection=local") $ANSIBLE_ARGS
}

linux() {
    if ! which ansible-playbook > /dev/null; then
        sudo apt update
        sudo apt install -qy ansible
    fi

    ansible-playbook ansible/ubuntu.yml -i <(echo "[localhost] localhost ansible_connection=local") $ANSIBLE_ARGS
}

if [[ "$(uname)" == "Darwin" ]]; then
    macos
fi

if [[ "$(uname)" == "Linux" ]]; then
    linux
fi