#!/bin/bash
set -e

# Install Homebrew
if ! which brew > /dev/null; then
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

if ! which ansible-playbook > /dev/null; then
    brew install ansible
fi

ansible-playbook macos.yml -i <(echo "[localhost] localhost ansible_connection=local")