---
- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Add nodesource repository
      shell: "curl -sL https://deb.nodesource.com/setup_11.x | sudo -E bash -"
      args:
        creates: /usr/bin/node
      tags: pkg

    - name: Add yarn pubkey
      shell: "curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -"
      args:
        creates: /usr/bin/yarn
      tags: pkg

    - name: Add yarn repository
      shell: "echo 'deb https://dl.yarnpkg.com/debian/ stable main' | sudo tee /etc/apt/sources.list.d/yarn.list"
      args:
        creates: /usr/bin/yarn
      tags: pkg

    - name: Install packages
      apt:
        name: "{{ packages }}"
        state: present
      become: yes
      tags: pkg
      vars:
        packages:
          - coreutils
          - build-essential
          - clang
          - lld
          - python3
          - python3-pip
          - gnupg
          - ruby
          - sudo
          - tmux
          - curl
          - wget
          - tree
          - git
          - mercurial
          - subversion
          - xorriso
          - qemu
          - grub-pc
          - docker.io
          - nodejs
          - yarn

    - name: "rust: Install rustup"
      shell: curl https://sh.rustup.rs -sSf | sh -s -- -y
      tags: rust
      args:
        creates: /home/seiya/.cargo/bin/rustup

    - name: "rust: Install nightly and set as default"
      command: rustup default nightly
      tags: rust

    - name: "rust: Install src"
      command: rustup component add rust-src
      tags: rust

    - name: "rust : Install clippy"
      command: rustup component add clippy-preview
      tags: rust

    - name: "rust : Install rustfmt"
      command: rustup component add rustfmt-preview
      tags: rust

    - name: "rust: Update components"
      command: rustup update
      tags: rust

    - name: Install Cargo apps
      command: "cargo install {{ item }}"
      tags: pkg
      loop: "{{ packages }}"
      vars:
        packages:
          - nsh
          - xargo
          - cargo-watch
          - cargo
          - loc

