- name: "mkdir"
  tags: link
  file:
    state: directory
    path: "{{ item.path }}"
    mode: "{{ item.mode }}"
  loop:
    - { mode: "0700", path: "~/.ssh" }
    - { mode: "0755", path: "~/.zsh" }
    - { mode: "0755", path: "~/.config/alacritty" }

- name: "Link ~/.* files"
  tags: link
  file:
    src: "~/.dotfiles/{{ item.src }}"
    dest: "{{ item.dst }}"
    state: link
  loop:
    - { src: "nshrc",           dst: "~/.nshrc" }
    - { src: "zshrc",           dst: "~/.zshrc" }
    - { src: "tmux.conf",       dst: "~/.tmux.conf" }
    - { src: "gitconfig",       dst: "~/.gitconfig" }
    - { src: "ssh_config",      dst: "~/.ssh/config" }
    - { src: "alacritty.yml",   dst: "~/.config/alacritty/alacritty.yml" }

#
#  zsh
#
- git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting
    dest: ~/.zsh/zsh-syntax-highlighting
    update: no

- git:
    repo: https://github.com/seebi/dircolors-solarized
    dest: ~/.zsh/dircolors-solarized
    update: no

- git:
    repo: https://github.com/zsh-users/zsh-completions
    dest: ~/.zsh/zsh-completions
    update: no
    
#
#  Rust toolchain
#
- name: "rust: Install nightly and set as default"
  command: ~/.cargo/bin/rustup default nightly
  tags: rust

- name: "rust: Install src"
  command: ~/.cargo/bin/rustup component add {{ item }}
  tags: rust
  loop:
    - rust-src
    - clippy-preview
    - rustfmt-preview

- name: Install Cargo apps
  command: "cargo install {{ item }}"
  tags: pkg
  loop:
    - loc
    - fd-find
    - ripgrep
    - cargo-watch

#
#  Visual Studio Code
#
- name: "vscode: Install extensions"
  command: code --install-extension "{{ item }}"
  tags: vscode
  loop: "{{ extensions }}"
  vars:
    extensions:
      - ms-vscode.cpptools
      - ms-vscode-remote.remote-ssh
      - ms-python.python
      - matklad.rust-analyzer
      - editorconfig.editorconfig
      - wayou.vscode-todo-highlight
      - zhuangtongfa.material-theme
