---
- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Install Homebrew packages
      homebrew:
        name: "{{ packages }}"
        state: present
      tags: pkg
      vars:
        packages:
          - coreutils
          - findutils
          - binutils
          - tmux
          - xz
          - gnu-tar
          - gnupg2
          - wget
          - jq
          - trash
          - git
          - mercurial
          - subversion
          - python
          - ruby
          - node
          - npm
          - yarn
          - rustup-init
          - nmap
          - tig
          - htop
          - pstree
          - docker
          - docker-machine
          - reattach-to-user-namespace
          - llvm
          - radare2
          - qemu
          - bochs
          - autoconf
          - autogen
          - automake
          - cmake
          - ghostscript

    - name: Install Apps
      homebrew_cask:
        name: "{{ packages }}"
        state: present
        # Prevent installing into ~/Applications.
        install_options: "appdir=/Applications"
      tags: pkg
      vars:
        packages:
          - google-chrome
          - firefox
          - alacritty
          - shiftit
          - karabiner-elements
          - keepingyouawake
          - wireshark
          - vlc
          - java
          - xquartz
          - mactex-no-gui
          - adobe-acrobat-reader
          - virtualbox
          - skim

    - name: Add homebrew/cask-fonts
      homebrew_tap:
        name: homebrew/cask-fonts
      tags: pkg

    - name: Install fonts
      homebrew_cask:
        name: "{{ fonts }}"
      vars:
        fonts:
          - font-m-plus
          - font-noto-sans
          - font-source-code-pro
      tags: pkg

    - name: "Apply bunch of defaults"
      osx_defaults:
        domain: "{{ item.domain }}"
        key: "{{ item.key }}"
        type: "{{ item.type }}"
        value: "{{ item.value }}"
      loop: "{{ defaults }}"
      tags: defaults
      vars:
        defaults:
          - domain: NSGlobalDomain
            key: AppleShowScrollBars
            type: string
            value: WhenScrolling
          # Expand the save dialog by default.
          - domain: NSGlobalDomain
            key: NSNavPanelExpandedStateForSaveMode
            type: bool
            value: true
          - domain: NSGlobalDomain
            key: NSNavPanelExpandedStateForSaveMode2
            type: bool
            value: true
          # Save a file on the local machine instead of iCloud by default.
          - domain: NSGlobalDomain
            key: NSDocumentSaveNewDocumentsToCloud
            type: bool
            value: false
          # Disable “Are you sure you want to open this application?”
          - domain: com.apple.LaunchServices
            key: LSQuarantine
            type: bool
            value: false
          # Disable Crash Repoter
          - domain: com.apple.CrashReporter
            key: DialogType
            type: string
            value: none
          # Disable spelling correction
          - domain: NSGlobalDomain
            key: NSAutomaticSpellingCorrectionEnabled
            type: bool
            value: false
          # Wipe out persistent Dock icons
          - domain: com.apple.dock
            key: persistent-apps
            type: array
            value: []
          - domain: com.apple.dock
            key: show-recents
            type: int
            value: 0
    # Apply changes
    - name: Restart Dock & Finder
      command: killall Finder && killall Dock
      tags: defaults

    - name: "Link macOS-specific files"
      tags: link
      file:
        src: "~/.dotfiles/{{ item.src }}"
        dest: "{{ item.dst }}"
        state: link
      loop:
        - { src: "karabinder.json", dst: "~/.config/karabiner/karabiner.json" }
        - { src: "vscode/settings.json",
            dst: "~/Library/Application Support/Code/User/settings.json" }
        - { src: "vscode/keybindings.json",
            dst: "~/Library/Application Support/Code/User/keybindings.json" }

    - import_tasks: common.yml