---
- hosts: localhost
  connection: local
  gather_facts: yes
  tasks:
    - name: Add nodesource repository
      shell: "curl -sL https://deb.nodesource.com/setup_current.x | sudo -E bash -"
      args:
        creates: /usr/bin/node
      tags: pkg

    - name: Add yarn pubkey
      shell: "curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -"
      args:
        creates: /usr/bin/yarn
      tags: pkg

    - name: Add yarn repository
      shell: "echo 'deb https://dl.yarnpkg.com/debian/ stable main' | sudo tee /etc/apt/sources.list.d/yarn.list"
      args:
        creates: /etc/apt/sources.list.d/yarn.list
      tags: pkg

    - name: Install packages for Docker Engine
      apt:
        name: "{{ packages }}"
        state: present
      become: yes
      tags: pkg
      vars:
        packages:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common

    - name: Add Docker pubkey
      shell: "curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -"
      args:
        creates: /usr/bin/docker
      tags: pkg

    - name: Add Docker repository
      shell: "echo 'deb https://download.docker.com/linux/ubuntu  {{ ansible_distribution_release }} stable' | sudo tee /etc/apt/sources.list.d/docker.list"
      args:
        creates: /etc/apt/sources.list.d/docker.list
      tags: pkg

    - name: Upgrade packages
      apt:
        upgrade: safe
        update_cache: yes
      become: yes
      tags: pkg
      
    - name: Install packages
      apt:
        name: "{{ packages }}"
        state: present
      become: yes
      tags: pkg
      vars:
        packages:
          - coreutils
          - build-essential
          - clang
          - lld
          - python3
          - python3-pip
          - gnupg
          - ruby
          - sudo
          - tmux
          - curl
          - wget
          - tree
          - git
          - mercurial
          - subversion
          - xorriso
          - qemu
          - grub-pc
          - nodejs
          - yarn
          - docker-ce
          - docker-ce-cli
          - containerd.io

    - name: "rust: Install rustup"
      shell: curl https://sh.rustup.rs -sSf | sh -s -- -y
      tags: rust
      args:
        creates: /home/seiya/.cargo/bin/rustup

    - name: Add seiya to user groups
      user:
        name: seiya
        groups:
          - docker
          - kvm
        append: yes
      become: yes
      
    - import_tasks: common.yml
